version: '3.1'


services:

  db_cadastro:
    container_name: db-cadastro
    image: mysql
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cadastro_db
      MYSQL_ROOT_PASSWORD: usuario123
      MYSQL_ROOT_USER: root
    ports:
      - "3306:3306"
    networks:
      - rede


volumes:
  mysql:


networks:
  rede: